<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.didattica.egoless.mine.nu/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://ws.didattica.egoless.mine.nu/" name="WSNazioneService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://ws.didattica.egoless.mine.nu/" schemaLocation="WSNazioneService_schema1.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </xsd:schema>
   <!-- <xsd:schema>
      <xsd:import namespace="http://api.ws.pqs.swellsys.com/" schemaLocation="http://localhost:8080/WSNazioneService/WSNazione/__container$publishing$subctx/META-INF/wsdl/WSNazioneService_schema2.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </xsd:schema> -->
  </types>
  <message name="recuperaNazioni">
    <part name="parameters" element="tns:recuperaNazioni"/>
  </message>
  <message name="recuperaNazioniResponse">
    <part name="parameters" element="tns:recuperaNazioniResponse"/>
  </message>
  <message name="WSDidatticaException">
    <part name="fault" element="tns:WSDidatticaException"/>
  </message>
  <portType name="WSNazione">
    <operation name="recuperaNazioni">
      <input message="tns:recuperaNazioni"/>
      <output message="tns:recuperaNazioniResponse"/>
      <fault name="WSDidatticaException" message="tns:WSDidatticaException"/>
    </operation>
  </portType>
  <binding name="WSNazionePortBinding" type="tns:WSNazione">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="recuperaNazioni">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="WSDidatticaException">
        <soap:fault name="WSDidatticaException" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="WSNazioneService">
    <port name="WSNazionePort" binding="tns:WSNazionePortBinding">
      <soap:address location="http://localhost:8080/WSDidattica/WSNazione" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"/>
    </port>
  </service>
</definitions>