/*
 * GestioneDatiStudentePanel.java
 *
 * Created on 9 marzo 2007, 1.52
 *
 * $Id$
 */

package nu.mine.egoless.didattica.app.gui.registroDocente;


import java.util.Date;
import nu.mine.egoless.didattica.app.bean.AssenzaBean;
import nu.mine.egoless.didattica.app.bean.MateriaInsegnamentoBean;
import nu.mine.egoless.didattica.app.bean.StudenteBean;
import nu.mine.egoless.didattica.app.bean.VotoBean;
import nu.mine.egoless.didattica.app.gui.componentiComuni.UtilitaGUI;
import nu.mine.egoless.didattica.ws.assenzaclient.Assenza;
import nu.mine.egoless.didattica.ws.personaclient.Studente;
import nu.mine.egoless.didattica.ws.personaclient.WSDidatticaException_Exception;
import nu.mine.egoless.didattica.ws.votoclient.Voto;


/**
 * Crea un pannello delegato alla gestione di uno studente.
 * Consente di visualizzare i dati anagrafici e scolastici,
 * e di inserirne voti ed assenze.
 *
 * @author  Alberto Meneghello
 */
public class GestioneDatiStudentePanel extends javax.swing.JPanel {
   
   /**
    * Crea un nuovo form GestioneDatiStudentePanel.
    * @param studente Studente a cui e' associato il pannello.
    * @prarm voto Voto associato allo studente (puo' essere null).
    * @param assenza  Assenza associata allo studente (puo' essere null).
    */
   public GestioneDatiStudentePanel (RegistroInsegnantePanel ancestor, RegistroPanel registro, MateriaInsegnamentoBean materia, Studente studente, Object dato, Date data) {
      try{
      this.ancestor = ancestor;
      this.registro = registro;
      this.dato = dato;
      ancestor.setValoreDownload (-1);
      this.studente = new StudenteBean();
      this.studente.caricaDaWS (studente.getId());
      System.out.println ("INIZIO CARICAMENTO DATI STUDENTE "+studente.getCognome ()+" "+studente.getNome () );
      if( dato instanceof Assenza )  { assenza = new AssenzaBean (); this.assenza.caricaDaWS ( ((Assenza)dato).getId () ); System.out.println ( "Caricata ASSENZA"); }
      else if( dato instanceof Voto ) { voto = new VotoBean (); this.voto.caricaDaWS ( ((Voto)dato).getId () ); System.out.println ( "Caricato VOTO"); }
      else System.out.println ( "ALBERTO: GestioneDatiStudentePanel: Non e' stata caricato nulla." );
      this.data = data;
      this.materia = materia;
      inizializzaComponenti ();
      caricaDati (studente, dato);
      ancestor.setValoreDownload (0);
      }catch(Exception e){
         new javax.swing.JOptionPane("Impossibile completare l'operazione.",javax.swing.JOptionPane.WARNING_MESSAGE ).setVisible(true);
       }
   }
   
   
   private void caricaDati (Studente studente, Object dato) {
      try {
         this.studente.caricaDaWS ( studente.getId () );
         if(dato instanceof Voto) this.voto.caricaDaWS ( ((Voto)dato).getId () );
         else if(dato instanceof Assenza) this.assenza.caricaDaWS ( ((Assenza)dato).getId () );
      } catch (UnsupportedOperationException ex) { ex.printStackTrace (); } catch (WSDidatticaException_Exception ex) { ex.printStackTrace (); } catch (Exception ex) { ex.printStackTrace (); }
   }
   
   /**
    * Inizializza le componenti graiche di GestioneDatiStudentePanel
    */
   private void inizializzaComponenti () {
      initComponents ();
      jpnlVisualizzaDatiStudente = new VisualizzaDatiStudentePanel (ancestor, studente);
      jtbpGestioneDatiStudente.addTab ("Visualizza dati", jpnlVisualizzaDatiStudente);
      jpnlGestioneVotiStudente = new GestioneVotiStudentePanel(ancestor, registro, studente, voto, materia, data);
      jpnlGestioneAssenzeStudente = new GestioneAssenzeStudentePanel (ancestor, registro, studente, assenza, data );
      jpnlGestioneDatiStudente.add (jpnlGestioneVotiStudente, this);
      jpnlGestioneDatiStudente.add (jpnlGestioneAssenzeStudente, this);
   }
   
   
   
   /**
    * This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents() {
      jtbpGestioneDatiStudente = new javax.swing.JTabbedPane();
      jpnlGestioneDatiStudente = new javax.swing.JPanel();
      jbChiudi = new javax.swing.JButton();

      setBackground(new java.awt.Color(153, 153, 255));
      setBorder(javax.swing.BorderFactory.createTitledBorder("Dati Studente"));
      jpnlGestioneDatiStudente.setLayout(new javax.swing.BoxLayout(jpnlGestioneDatiStudente, javax.swing.BoxLayout.Y_AXIS));

      jpnlGestioneDatiStudente.setBackground(new java.awt.Color(204, 204, 255));
      jtbpGestioneDatiStudente.addTab("Voto / Assenza", jpnlGestioneDatiStudente);

      jbChiudi.setText("Chiudi");
      jbChiudi.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbChiudiActionPerformed(evt);
         }
      });

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jtbpGestioneDatiStudente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .addContainerGap(281, Short.MAX_VALUE)
            .add(jbChiudi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(jtbpGestioneDatiStudente, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jbChiudi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
      );
   }// </editor-fold>//GEN-END:initComponents
   
   
   /**
    * Chiude il pannello dei dati dello studente
    */
   private void jbChiudiActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChiudiActionPerformed
      ancestor.chiudiGestioneDatiStudente (this);
   }//GEN-LAST:event_jbChiudiActionPerformed
   
   
   
   /**
    * Controlla se il pannello e' associato ad uno specifico studente.
    * @param studente Lo studente da testare.
    * @return true se e solo se lo studente corrispondente al pannello.
    */
   public boolean corrispondeA (Studente studente) {
      return this.studente.getId () == studente.getId ();
   }
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jbChiudi;
   private javax.swing.JPanel jpnlGestioneDatiStudente;
   private javax.swing.JTabbedPane jtbpGestioneDatiStudente;
   // End of variables declaration//GEN-END:variables
   
   private VisualizzaDatiStudentePanel jpnlVisualizzaDatiStudente;
   private GestioneVotiStudentePanel jpnlGestioneVotiStudente;
   private GestioneAssenzeStudentePanel jpnlGestioneAssenzeStudente;
   
   private RegistroInsegnantePanel ancestor;
   
   /** Studente a cui si riferisce il pannello */
   private StudenteBean studente;
   /** Voto associato allo studente a cui si riferisce il pannello */
   private VotoBean voto;
   /** Assenza associata allo studente a cui si riferisce il pannello */
   private AssenzaBean assenza;
   /** Data del registro */
   
   private Date data;
   private MateriaInsegnamentoBean materia;
   private Object dato;
   private RegistroPanel registro;
   
   
   /**
    * Avvia un'anteprima dell'interfaccia grafica.
    */
   public static void main (String[] args) {
      String str = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";	// Windows
      //String str = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";		// Grey
      //String str = "javax.swing.plaf.metal.MetalLookAndFeel";   			// Java Metal
      try { javax.swing.UIManager.setLookAndFeel (str); } catch (Exception ex) { System.out.println ("Failed loading Look And Feel:\n"+ex+'\n'); }
      javax.swing.JFrame temp=new javax.swing.JFrame ();
      temp.setLayout (new java.awt.BorderLayout ());
      
      Studente studente = new Studente ();
      studente.setId (1);
      studente.setMatricola ("518667");
      studente.setNome ("Alberto");
      studente.setCognome ("Meneghello");
      studente.setCodiceFiscale ("MNGLRT85L08L585S");
      //studente.setDataNascita (new Date(85,6,8) );
      studente.setPortatoreHandicap (true);
      
      AssenzaBean assenza = new AssenzaBean ();
      assenza.setDataInizio (new Date (107,2,20 ));
      assenza.setDataFine (new Date (107,2,22 ));
      
      
      temp.add (new GestioneDatiStudentePanel (null, null,null, studente, assenza, UtilitaGUI.getDataCorrente () ));
      temp.setSize (300,400);
      temp.setVisible (true);
   }
   
}
