/*
 * ListaVotiStudentePanel.java
 *
 * Created on 10 marzo 2007, 21.55
 *
 * $Id$
 */

package nu.mine.egoless.didattica.app.gui.registroDocente;

import java.util.Vector;
import nu.mine.egoless.didattica.app.bean.VotiBean;
import nu.mine.egoless.didattica.app.bean.VotoBean;
import nu.mine.egoless.didattica.app.gui.componentiComuni.ContenitoreDati;
import nu.mine.egoless.didattica.app.gui.componentiComuni.UtilitaGUI;
import nu.mine.egoless.didattica.ws.materiaclient.MateriaInsegnamento;
import nu.mine.egoless.didattica.ws.tipoprovaclient.TipoProva;
import nu.mine.egoless.didattica.ws.tipovotoclient.TipoVoto;


/**
 * Visualizza tutti i voti dello studente
 *
 * @author  Admin
 */
public class ListaVotiStudentePanel extends javax.swing.JPanel {
   
   /**
    * Creates new form ListaVotiStudentePanel
    */
   public ListaVotiStudentePanel ( Vector<VotoBean> voti, String materia, ContenitoreDati dati ) {//  , int idMateria) {
      this.voti = voti;
      this.dati = dati;
      initComponents ();
      visualizzaDati(materia);
   }
   
   
   
   private void visualizzaDati (String materia) {      
      setBorder(javax.swing.BorderFactory.createTitledBorder( "Valutazioni in "+materia ));

      for(int i=0; i < voti.size(); i++ ){
         
         int idTipoVoto = voti.elementAt (i).getIdTipoVoto (),
             idTipoProva = voti.elementAt (i).getIdTipoProva ();
         
         String tipoVoto = "-",
                tipoProva = "-",
                descrizione = voti.elementAt (i).getDescrizione (),
                data = UtilitaGUI.dateToString ( voti.elementAt (i).getData() );           // E' ancora in formato java.util.Date
         
         TipoVoto tVoto = UtilitaGUI.getTipoVoto ( dati.getTipiVoto(), idTipoVoto);
         if(tVoto!=null) tipoVoto = tVoto.getNome();
         
         TipoProva tProva = UtilitaGUI.getTipoProva ( dati.getTipiProve (), idTipoProva);
         if(tProva!=null) tipoProva = tProva.getNome();
         
         Object[] riga = {  tipoVoto, tipoProva, data, descrizione };
         UtilitaGUI.inserisciRiga ( jtblListaVotiMateria, i, riga );
      }   
   }
   
   
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents() {
      jscpListaVotiMateria = new javax.swing.JScrollPane();
      jtblListaVotiMateria = new javax.swing.JTable();

      jtblListaVotiMateria.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "Valore", "Tipo Prova", "Data", "Descrizione"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
         };
         boolean[] canEdit = new boolean [] {
            false, false, false, true
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      jscpListaVotiMateria.setViewportView(jtblListaVotiMateria);

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jscpListaVotiMateria, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .add(jscpListaVotiMateria, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane jscpListaVotiMateria;
   private javax.swing.JTable jtblListaVotiMateria;
   // End of variables declaration//GEN-END:variables
   
   private Vector<VotoBean> voti;
   private ContenitoreDati dati;
   
   
   
    /**
     * Avvia un'anteprima dell'interfaccia grafica.
     */
    public static void main(String[] args) {
        String str = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";	// Windows
	//String str = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";		// Grey
	//String str = "javax.swing.plaf.metal.MetalLookAndFeel";   			// Java Metal
	try { javax.swing.UIManager.setLookAndFeel(str); }
	catch (Exception ex) { System.out.println("Failed loading Look And Feel:\n"+ex+'\n'); }
        javax.swing.JFrame temp=new javax.swing.JFrame();
        temp.setLayout(new java.awt.BorderLayout());
        temp.add(new ListaVotiStudentePanel(null,null,null ));
        temp.setSize(320,240);
        temp.setVisible(true);
    }
   
   
}
