/*
 * BarraDiStatoPanel.java
 *
 * Created on 2 marzo 2007, 21.15
 */

package nu.mine.egoless.didattica.app.gui.componentiComuni;

/**
 *
 * @author  Lorenzo Daniele
 *
 * Pannello che implementa una barra di stato con due barre di progresso per il download
 * e l'upload dei dati e una label
 */
public class BarraDiStatoPanel extends javax.swing.JPanel implements BarraDiStatoCompatibile{
    
    /** 
     * Creates new form BarraDiStatoPanel 
     */
    public BarraDiStatoPanel(){
        initComponents();
    }
    
    /**
     * Setta il testo nella label di stato
     */
    public void setTesto(String testo) {
        jlblStato.setText(testo);
    }
    
    /**
     *Setta il valore nella barra indicante il progresso di uploading appartenente a [1...100]
     */
    public void setValoreUpload(int n) {
        jprgUpload.setValue(n);
    }
    
    /**
     * Setta il valore nella barra indicante il progresso di downloading appartenente a [1...100]
     */
    public void setValoreDownload(int n) {
        jprgDownload.setValue(n);
    }    
    
    /**
     * setta, se b è true, la barra di upload in stato indeterminato
     */
    public void setUploadIndeterminato(boolean b){
        if(b){
           jprgUpload.setValue(0);
           jprgUpload.setIndeterminate(true);
        } else {
           jprgUpload.setIndeterminate(false);
           jprgUpload.setValue(0);   
        }
    }

    /**
     * setta, se b è true, la barra di download in stato indeterminato
     */    
    public void setDownloadIndeterminato(boolean b){
        if(b){
           jprgDownload.setValue(0);
           jprgDownload.setIndeterminate(true);
        } else {
           jprgDownload.setIndeterminate(false);
           jprgDownload.setValue(0);   
        }
    }    

    /**
     * main di prova
     */
    public static void main(String[] args) {
        javax.swing.JDialog temp=new javax.swing.JDialog();
        temp.setLayout(new java.awt.BorderLayout());
        temp.add(new BarraDiStatoPanel());
        temp.setSize(500,500);
        temp.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jlblStato = new javax.swing.JLabel();
        jlblDownload = new javax.swing.JLabel();
        jprgDownload = new javax.swing.JProgressBar();
        jlblUpload = new javax.swing.JLabel();
        jprgUpload = new javax.swing.JProgressBar();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));

        jlblStato.setText(" Benvenuto in SGIQA! ");
        jlblStato.setPreferredSize(new java.awt.Dimension(200, 14));
        add(jlblStato);

        jlblDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nu/mine/egoless/didattica/app/gui/img/Import16.gif")));
        jlblDownload.setDoubleBuffered(true);
        add(jlblDownload);

        jprgDownload.setForeground(new java.awt.Color(0, 204, 0));
        jprgDownload.setToolTipText("indndicatore del processo di download");
        add(jprgDownload);

        jlblUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nu/mine/egoless/didattica/app/gui/img/Export16.gif")));
        add(jlblUpload);

        jprgUpload.setForeground(new java.awt.Color(255, 0, 0));
        jprgUpload.setToolTipText("Indicatore del processo di upload");
        add(jprgUpload);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblDownload;
    private javax.swing.JLabel jlblStato;
    private javax.swing.JLabel jlblUpload;
    private javax.swing.JProgressBar jprgDownload;
    private javax.swing.JProgressBar jprgUpload;
    // End of variables declaration//GEN-END:variables
    
}
