/*
 * ModificaListaElementiDialog.java
 *
 * Created on 6 marzo 2007, 22.52
 */

package nu.mine.egoless.didattica.app.gui.componentiComuni;


import java.util.Vector;
import nu.mine.egoless.didattica.app.gui.componentiComuni.Listable;
import nu.mine.egoless.didattica.app.gui.componentiComuni.elementi.ElementoClasse;



/**
 * La classe consente di modificare una lista di elementi semplici.
 * 
 * @author  Lorenzo Daniele
 * @author  Alberto Meneghello
 */
public class ModificaListaElementiDialog<Tipo extends Listable> extends javax.swing.JDialog {
    
   
    /**
    * Crea un nuovo form ModificaListaElementiDialog attraverso
    * cui modificare la lista 
    */
    public ModificaListaElementiDialog(java.awt.Frame parent, boolean modal, String descrizioneOggettoModificato, Vector<Tipo> lista) {
        super(parent, modal);
        this.descrizioneOggettoModificato = descrizioneOggettoModificato;
        listaElementi = lista;
        inizializzaComponenti();
    }
    
    /**
     * Inizializza le componenti grafiche della GUI.
     */
    public void inizializzaComponenti() {
        initComponents();
        jlstListaMaterie.setListData(listaElementi);
        javax.swing.border.Border border = jpnlModificaMaterie.getBorder();
        if(border instanceof javax.swing.border.TitledBorder)
            ((javax.swing.border.TitledBorder)border).setTitle("Modifica "+descrizioneOggettoModificato);
    }
    
    
    /** 
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents() {
      jpnlModificaMaterie = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      jlstListaMaterie = new javax.swing.JList();
      jbEliminaMateria = new javax.swing.JButton();
      jbChiudi = new javax.swing.JButton();
      jtfMateria = new javax.swing.JTextField();
      jbAggiungiMateria = new javax.swing.JButton();
      jlblStato = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setAlwaysOnTop(true);
      setForeground(java.awt.Color.gray);
      setModal(true);
      jpnlModificaMaterie.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifica Lista"));
      jlstListaMaterie.setModel(new javax.swing.AbstractListModel() {
         String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jScrollPane1.setViewportView(jlstListaMaterie);

      jbEliminaMateria.setText("Elimina");
      jbEliminaMateria.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            eliminaElementoActionPerformed(evt);
         }
      });

      jbChiudi.setText("Chiudi");
      jbChiudi.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            chiudiDialogActionPerformed(evt);
         }
      });

      jbAggiungiMateria.setText("Aggiungi");
      jbAggiungiMateria.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            aggiungiElementoActionPerformed(evt);
         }
      });

      jlblStato.setText("Attendere...");

      org.jdesktop.layout.GroupLayout jpnlModificaMaterieLayout = new org.jdesktop.layout.GroupLayout(jpnlModificaMaterie);
      jpnlModificaMaterie.setLayout(jpnlModificaMaterieLayout);
      jpnlModificaMaterieLayout.setHorizontalGroup(
         jpnlModificaMaterieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jpnlModificaMaterieLayout.createSequentialGroup()
            .addContainerGap()
            .add(jpnlModificaMaterieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jlblStato, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
               .add(jpnlModificaMaterieLayout.createSequentialGroup()
                  .add(jpnlModificaMaterieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                     .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                     .add(org.jdesktop.layout.GroupLayout.LEADING, jtfMateria, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                  .add(jpnlModificaMaterieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                     .add(org.jdesktop.layout.GroupLayout.TRAILING, jbEliminaMateria, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                     .add(jbAggiungiMateria, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                     .add(jbChiudi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
            .addContainerGap())
      );
      jpnlModificaMaterieLayout.setVerticalGroup(
         jpnlModificaMaterieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jpnlModificaMaterieLayout.createSequentialGroup()
            .add(jpnlModificaMaterieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
               .add(jtfMateria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
               .add(jbAggiungiMateria))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jpnlModificaMaterieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jpnlModificaMaterieLayout.createSequentialGroup()
                  .add(jbEliminaMateria)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 93, Short.MAX_VALUE)
                  .add(jbChiudi))
               .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jlblStato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
      );

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnlModificaMaterie, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(jpnlModificaMaterie, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      pack();
   }// </editor-fold>//GEN-END:initComponents

   
   
   public void aggiornaLista () {
      jlstListaMaterie.setListData(listaElementi);
   }
   
   
   private void chiudiDialogActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiudiDialogActionPerformed
     setVisible(false);
   }//GEN-LAST:event_chiudiDialogActionPerformed

   
   
   private void eliminaElementoActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaElementoActionPerformed
      Tipo elementoDaEliminare = (Tipo) (jlstListaMaterie.getSelectedValue() );
      listaElementi.remove(elementoDaEliminare);
      aggiornaLista();
   }//GEN-LAST:event_eliminaElementoActionPerformed

   
   private void aggiungiElementoActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiElementoActionPerformed
      Tipo nuovoElemento = listaElementi.elementAt(0);
      String nuovo = jtfMateria.getText();
      //nuovoElemento = 
         //nuovoElemento.fromString( jtfMateria.getText() );
      if( nuovo.length () >1 )  {
            listaElementi.add ( (Tipo)(nuovoElemento.fromString( jtfMateria.getText() )) ); 
            aggiornaLista();
      }
   }//GEN-LAST:event_aggiungiElementoActionPerformed
   
   
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //String[] str = { "Red", "Green", "Blue", "Yellow", "Orange", "Violet" };
                String[] str = { "1A", "2A", "3B", "4B", "5A", "5B" };
                Vector<ElementoClasse> elementi = new Vector<ElementoClasse>();
                for(int i=0; i<str.length; i++) { elementi.add( new ElementoClasse(0, str[i]) ) ; }
                
                System.out.println ( new ElementoClasse(0, "Alberto") );
                
                new ModificaListaElementiDialog<ElementoClasse>(new javax.swing.JFrame(), true, "Lista Materie", elementi).setVisible(true);
            }
        });
    }
    
    
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JButton jbAggiungiMateria;
   private javax.swing.JButton jbChiudi;
   private javax.swing.JButton jbEliminaMateria;
   private javax.swing.JLabel jlblStato;
   private javax.swing.JList jlstListaMaterie;
   private javax.swing.JPanel jpnlModificaMaterie;
   private javax.swing.JTextField jtfMateria;
   // End of variables declaration//GEN-END:variables
 
   private Vector<Tipo> listaElementi;
   private String descrizioneOggettoModificato;
   
}


