/*
 * GestioneDatiPanel.java
 *
 * Created on 8 marzo 2007, 23.47
 */

package nu.mine.egoless.didattica.app.gui.gestionePersone;

/**
 *
 * @author  Lorenzo Daniele
 *
 * Estensione di JPanel che racchiude i metodi comuni a quei pannelli il cui
 * scopo è permettere la gestione dei dati di una particolare persona (studente, insegnante ...)
 */
public abstract class GestionePersonaPanel extends javax.swing.JPanel {
    
    /** 
     * Creates new form GestioneDatiPanel 
     * @param jpnlAncestor il GestioneTabPanel che contiene tale GestionePersonaPanel
     */
    public GestionePersonaPanel(GestioneTabPanel jpnlAncestor) {
        if(jpnlAncestor == null) throw new IllegalArgumentException();       
        this.jpnlAncestor = jpnlAncestor;
        initComponents();
    }
    
    /**
     * Ritorna il GestioneTabPanel in cui tale GestionePersonaPanel è contenuto
     */
    public GestioneTabPanel getAncestor(){ return jpnlAncestor; }
    
    /**
     * Il panel deve ritornare un id che lo identifichi. Di Utilità per impedire
     * che vengano aperte due GestionePersonaPanel contemporaneamente per la stessa persona
     */
    public abstract int getId();
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**variabili locali*/
    private GestioneTabPanel jpnlAncestor = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
