/*
 * RicercaPersonePanel.java
 *
 * Created on 8 marzo 2007, 23.47
 */

package nu.mine.egoless.didattica.app.gui.gestionePersone;

/**
 *
 * @author  Lorenzo Daniele
 *
 * Estensione di JPanel che contiene i metodi comuni a quei pannelli 
 * il cui scopo sia quello di implementare la parte grafica 
 * di una ricerca di persone all'interno di un database
 */
public class RicercaPersonePanel extends javax.swing.JPanel {
    
    /**
     * Creates new form RicercaPersonePanel
     * @param jpnlAncestor il GEstioneTabPanel che contiene tale RicercaPErsonaPanel
     */
    public RicercaPersonePanel(GestioneTabPanel jpnlAncestor) {
        if(jpnlAncestor == null) throw new IllegalArgumentException();
        this.jpnlAncestor = jpnlAncestor;
    }
    
    /** 
     * ritorna il GestioneTabPanel in cui tale RicercaPersonePanel è contenuto
     */
    public GestioneTabPanel getAncestor(){ return jpnlAncestor;}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * Nell'implementazione corrente tale metodo è inutile
     */
    /*
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    */
     
    /**variabili locali*/
    private GestioneTabPanel jpnlAncestor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
