/*
 * GestioneTabInsegnantiPanel.java
 *
 * Created on 8 marzo 2007, 23.54
 */

package nu.mine.egoless.didattica.app.gui.gestionePersone.insegnanti;

import nu.mine.egoless.didattica.app.bean.NazioniBean;
import nu.mine.egoless.didattica.app.bean.ReligioniBean;
import nu.mine.egoless.didattica.app.bean.ClassiBean;
import nu.mine.egoless.didattica.app.bean.MaterieInsegnamentoBean;
import nu.mine.egoless.didattica.app.bean.TipiVotiBean;
import nu.mine.egoless.didattica.app.bean.TipiAssenzeBean;
import nu.mine.egoless.didattica.app.gui.componentiComuni.ContenitoreDati;
import nu.mine.egoless.didattica.app.gui.gestionePersone.*;
/**
 *
 * @author  Lorenzo Daniele
 *
 * Classe che implementa un pannello che contiene due tabbed pane divisi da un
 * separatore verticale. Lo scopo è quello di gestire tali due tabbed pane ed  
 * i pannelli in essi contenuti
 * Contiene un BarraDiStatoPanel
 */
public class GestioneTabInsegnantiPanel extends GestioneTabPersonePanel {
    
    /**
     * Creates new form GestioneTabInsegnantiPanel
     * @param cont il contenitore dei dati caricati inizialmente dall'applicazione
     */
    public GestioneTabInsegnantiPanel(ContenitoreDati cont) {
        super();
        if(cont == null) throw new IllegalArgumentException();
        this.contenitore = cont;        
        inizializzaComponenti();
        setTesto("Benvenuto in SGIQA - Gestione Insegnanti");
    }
    
    /**
     * Cancella da ogni RisultatiRicercaStudentiPanel il risultato con id indicato e rivisualizza i risultati
     */
    public void cancellaDaiRisultati(int id){
        for( int i=0; i<getTabbedPaneSx().getTabCount(); i++){
            java.awt.Component comp = getTabbedPaneSx().getComponentAt(i);
            if( comp instanceof RicercaInsegnantiPanel){
                ((RicercaInsegnantiPanel) comp).cancellaRisultatoRicercaERivisualizza(id);
            }
            else System.out.println("GestioneTabStudenti: Tipo imprevisto");
        }
    }    
    
    /**
     * inizializza le componenti grafiche del pannello
     */    
    private void inizializzaComponenti(){
        apriNuovoPannelloSx();
        //apriNuovoPannelloDx();        
    }    
    
    /**
     * Ritorna un nuovo pannello del tipo contenuto nel tabbed pane di sinistra
     **/       
    protected RicercaInsegnantiPanel getNuovoPannelloSx(){return new RicercaInsegnantiPanel(this, contenitore);}

    /**
     * Ritorna un nuovo pannello del tipo contenuto nel tabbed pane di destra
     **/       
    protected GestioneInsegnantePanel getNuovoPannelloDx(){return new GestioneInsegnantePanel(this, contenitore);}    

    /**
     * Ritorna un nuovo pannello del tipo contenuto nel tabbed pane di destra
     * @param id l'identificativo univoco nel database dello studente i cui dati devono essere gestiti
     */    
    protected GestioneInsegnantePanel getNuovoPannelloDx(int id){ return new GestioneInsegnantePanel(this, contenitore, id); }

    /**
     * main di prova
     **/    
    public static void main(String[] args) {
//        javax.swing.JDialog temp=new javax.swing.JDialog();
//        temp.setLayout(new java.awt.BorderLayout());
//        ContenitoreDati c = new ContenitoreDati(new ReligioniBean(), new NazioniBean(), new ClassiBean(), new MaterieInsegnamentoBean(), new TipiVotiBean(), new TipiAssenzeBean());
//        GestioneTabPanel t=new GestioneTabInsegnantiPanel(c);
//        temp.add(t);
//        //t.apriNuovoPannelloSx();
//        //t.apriNuovoPannelloDx();
//        t.setSize(500,500);
//        temp.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     * Nell'implementazione corrente tale metodo è inutile
     */
    /*
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    */
    
    /**variabili locali*/
    private ContenitoreDati contenitore = null;   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
